[workspace]
members = [
    "crates/pit-c-generic",
    "crates/pit-go-generic",
    "crates/pit-haxe-generic",
    "crates/pit-rust-generic",
    "crates/pit-swift-generic",
    "crates/pit-to-capnp",
    "crates/pit-ts-generic",
    "crates/pit-wit-bridge",
]
resolver = "3"

[workspace.dependencies]
pit-core = { version = "^0.4.8", git = "https://github.com/portal-co/pit-core.git" }
instability = "0.3.7"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
portal-solutions-sdk = { version = "0.0.2", git = "https://github.com/portal-co/portal-solutions-sdk.git" }
