[workspace]
members=[ "pit-c-generic", "pit-go-generic", "pit-haxe-generic","pit-rust-generic", "pit-swift-generic", "pit-ts-generic"]
resolver="3"

[workspace.dependencies]
pit-core = "0.4.2"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
