[package]
name = "pit-ts-generic"
version = "0.0.0"
edition = "2024"
license = "MPL-2.0"
description = "Generic PIT bindings"

[dependencies]

hex = { version = "0.4.3", default-features = false, features = ["alloc"] }

pit-core.workspace = true
