[package]
name = "pit-rust-generic"
version = "0.1.0"
edition = "2024"

[dependencies]
hex.workspace = true

pit-core.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
