[package]
name = "pit-rust-generic"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"


pit-core.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
